name: Daily Commit

on:
  schedule:
    - cron: '0 12 * * *'
    - cron: '30 18 * * 1,3,5'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - name: Append current date to activity_log.txt
        run: |
          echo "$(date)" >> activity_log.txt

      - name: Commit and push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add activity_log.txt
          git commit -m "Automated commit on $(date)" || echo "No changes to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
