name: Daily Commit

on:
  schedule:
    - cron: '0 12 * * *'  # Runs daily at 12:00 UTC (5 AM PDT)
  workflow_dispatch:       # Optional: allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - name: Append current date to activity_log.txt
        run: |
          echo "$(date)" >> activity_log.txt

      - name: Commit and push
        run: |
          git add activity_log.txt
          git commit -m "Automated commit on $(date)" || echo "No changes to commit"
          git push
